sample subscriptions added to hapi server
amida-tech/amida-hapi pull request #1
Opened 2018-08-14 18:50 UTC by morleegan

Added sample subscriptions to Hapi Fhir

2018-08-16 04:36 UTC, Perry5 approved these changes

2018-08-16 16:19 UTC, mhiner requested changes
Channel is delivery, not source.  I would like to see deliveries to kafka (type = message) and rest hook (this can be a arbitrary location but we will need something to respond during tests for gateway)

https://www.hl7.org/fhir/DSTU2/subscription.html

2018-09-05 16:27 UTC, morleegan commented
@mhiner - check this again, just updated it.

2018-09-07 14:25 UTC, mhiner approved these changes
This is fine, I would like for is to have samples of rest-hook and socket but there is no need to hold up this PR for that.

2018-09-07 14:31 UTC, merged